version: '3.8'

services:
    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - php
            - mysql_db
    # App Service
    php:
        container_name: php
        build: 
            context: ./Docker
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www
    # Mysql Database Service
    mysql_db:
        image : mysql
        container_name : mysql
        volumes:
            - ./database/mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: blog
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: password
    # Postgres Database Service
    # postgres_db:
    #     image: postgres
    #     container_name: postgres
    #     volumes:
    #         - ./database/postgresql/data:/var/lib/postgresql/data
    #     ports:
    #         - "5432:5432"
    #     environment: 
    #         POSTGRES_DB: blog
    #         POSTGRES_USER: root 
    #         POSTGRES_PASSWORD: password
    # PhpMyAdmin Service
    phpmyadmin:
       image: phpmyadmin/phpmyadmin
       container_name: phpmyadmin
       ports:
            - "3400:80"
       depends_on:
            - mysql_db
    # Pgadmin Service
    # pgadmin:
    #     image: dpage/pgadmin4
    #     container_name: pgAdmin
    #     ports:
    #         - "5050:80"
    #     depends_on:
    #         - db 
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: testing@gmail.com
    #         PGADMIN_DEFAULT_PASSWORD: password